# Generated by Django 5.2.6 on 2025-09-14 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerificationLog',
        ),
    ]
