# Generated by Django 5.2.6 on 2025-09-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_alter_drug_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='manufacturer_date',
            field=models.DateField(),
        ),
    ]
